/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication1.Inventory.MySqlConnection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sathu
 */
public class Finance2EmpSAL extends javax.swing.JFrame {

    /**
     * Creates new form Finance2
     */
    public Finance2EmpSAL() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setVisible(true);
        loadSupplier();
        //loadSupplieradd();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       fillTable();
    }
     public ArrayList<Finance2EmpSALbean>retrieveData(){
        
        ArrayList<Finance2EmpSALbean> al=null;
        
        al=new ArrayList<Finance2EmpSALbean>();
        
        try{
            Connection conn=MySqlConnection();
            String qry="select * from financesalary";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(qry);
            Finance2EmpSALbean cus;
        
            while(rs.next()){
            
            cus=new Finance2EmpSALbean(rs.getString("Name"),rs.getInt("Eid"),rs.getString("BasicSalary"),rs.getString("OverTime"),rs.getString("WorkingDays"),rs.getString("RateperHours"),rs.getString("Bonus"),rs.getString("Total"));
             al.add(cus);
        }  
        }
        
        
        catch(Exception e){
            System.out.println(e);
            
        }
        
        return al;
        
    }
    
    public void fillTable(){
        
        ArrayList<Finance2EmpSALbean> al=retrieveData();
        DefaultTableModel model=(DefaultTableModel)jTableEmp.getModel();
        model.setRowCount(0);
        Object[]row=new Object[8];
                
                for(int i=0; i<al.size(); i++){
                    
                    row[0]=al.get(i).getName();
                    row[1]=al.get(i).getEid();
                    row[2]=al.get(i).getBasicSalary();
                    row[3]=al.get(i).getOverTime();
                    row[4]=al.get(i).getWorkingDays();
                    row[5]=al.get(i).getRatePerHours();
                    row[6]=al.get(i).getBonus();
                    row[7]=al.get(i).getTotal();
                    model.addRow(row);
                }
        
        
    }
     public void loadSupplier(){
    
        try {
            Connection conn=MySqlConnection();
            
            String query="SELECT * FROM salary";
            PreparedStatement ps=conn.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            
            while(rs.next()){
                String SupplierName=rs.getString("name");
                cb_supplier1.addItem(SupplierName);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        cb_supplier1 = new javax.swing.JComboBox<>();
        txtsupplierid1 = new javax.swing.JTextField();
        txtsupplierid2 = new javax.swing.JTextField();
        txtsupplierid3 = new javax.swing.JTextField();
        txtsupplierid4 = new javax.swing.JTextField();
        txtsupplierid5 = new javax.swing.JTextField();
        txtsupplierid6 = new javax.swing.JTextField();
        txtsupplierid7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonsubmit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmp = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jSeparator1.setBackground(new java.awt.Color(255, 0, 51));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 100, 1360, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1210, 30, 90, 30);

        cb_supplier1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cb_supplier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_supplier1ActionPerformed(evt);
            }
        });
        jPanel1.add(cb_supplier1);
        cb_supplier1.setBounds(260, 130, 260, 40);

        txtsupplierid1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsupplierid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplierid1ActionPerformed(evt);
            }
        });
        txtsupplierid1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsupplierid1KeyReleased(evt);
            }
        });
        jPanel1.add(txtsupplierid1);
        txtsupplierid1.setBounds(260, 190, 260, 40);

        txtsupplierid2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsupplierid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplierid2ActionPerformed(evt);
            }
        });
        txtsupplierid2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsupplierid2KeyReleased(evt);
            }
        });
        jPanel1.add(txtsupplierid2);
        txtsupplierid2.setBounds(260, 250, 260, 40);

        txtsupplierid3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsupplierid3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplierid3ActionPerformed(evt);
            }
        });
        txtsupplierid3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsupplierid3KeyReleased(evt);
            }
        });
        jPanel1.add(txtsupplierid3);
        txtsupplierid3.setBounds(260, 310, 260, 40);

        txtsupplierid4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsupplierid4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplierid4ActionPerformed(evt);
            }
        });
        txtsupplierid4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsupplierid4KeyReleased(evt);
            }
        });
        jPanel1.add(txtsupplierid4);
        txtsupplierid4.setBounds(260, 370, 260, 40);

        txtsupplierid5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsupplierid5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplierid5ActionPerformed(evt);
            }
        });
        txtsupplierid5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsupplierid5KeyReleased(evt);
            }
        });
        jPanel1.add(txtsupplierid5);
        txtsupplierid5.setBounds(260, 430, 260, 40);

        txtsupplierid6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsupplierid6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplierid6ActionPerformed(evt);
            }
        });
        txtsupplierid6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsupplierid6KeyReleased(evt);
            }
        });
        jPanel1.add(txtsupplierid6);
        txtsupplierid6.setBounds(260, 490, 260, 40);

        txtsupplierid7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtsupplierid7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplierid7ActionPerformed(evt);
            }
        });
        txtsupplierid7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsupplierid7KeyReleased(evt);
            }
        });
        jPanel1.add(txtsupplierid7);
        txtsupplierid7.setBounds(260, 550, 260, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Total");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 550, 80, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Employee Salary calculation");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 20, 570, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Employee ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 180, 170, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Basic Salary");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 240, 160, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Over Time");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 300, 140, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Working Days");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 360, 190, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Rate per Hours");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 420, 190, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Bouns");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(170, 480, 90, 50);

        jButtonsubmit.setBackground(new java.awt.Color(51, 204, 0));
        jButtonsubmit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        jButtonsubmit.setText("SUBMIT");
        jButtonsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsubmit);
        jButtonsubmit.setBounds(400, 640, 180, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Employee Name");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 120, 210, 50);

        jTableEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee name", "Emloyee ID", "Basic Salary", "Over Time", "Working Days", "Rate /Hours", "Bouns", "Total Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEmp);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(540, 130, 790, 480);

        jButton3.setText("Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1210, 640, 120, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Finance1 rr= new Finance1();
        rr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_supplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_supplier1ActionPerformed

        try {
            String sName=cb_supplier1.getSelectedItem().toString();

            Connection conn=MySqlConnection();
            String query="SELECT * FROM salary WHERE name='"+sName+"'";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while(rs.next()){
                Integer sNum=rs.getInt("eid");
                txtsupplierid1.setText(sNum.toString());
                Integer sNum2=rs.getInt("BasicSalary");
                txtsupplierid2.setText(sNum2.toString());
                Integer sNum3=rs.getInt("Overtime");
                txtsupplierid3.setText(sNum3.toString());
                Integer sNum4=rs.getInt("WorkingDays");
                txtsupplierid4.setText(sNum4.toString());
                Integer sNum5=rs.getInt("RatePerHours");
                txtsupplierid5.setText(sNum5.toString());
                Integer sNum6=rs.getInt("Bonus");
                txtsupplierid6.setText(sNum6.toString());
                Integer Total=(sNum2+(sNum3*sNum5)+sNum6);
                txtsupplierid7.setText(Total.toString());
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Finance2EmpSAL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cb_supplier1ActionPerformed

    private void txtsupplierid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplierid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid1ActionPerformed

    private void txtsupplierid1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupplierid1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid1KeyReleased

    private void txtsupplierid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplierid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid2ActionPerformed

    private void txtsupplierid2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupplierid2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid2KeyReleased

    private void txtsupplierid3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplierid3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid3ActionPerformed

    private void txtsupplierid3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupplierid3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid3KeyReleased

    private void txtsupplierid4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplierid4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid4ActionPerformed

    private void txtsupplierid4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupplierid4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid4KeyReleased

    private void txtsupplierid5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplierid5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid5ActionPerformed

    private void txtsupplierid5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupplierid5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid5KeyReleased

    private void txtsupplierid6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplierid6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid6ActionPerformed

    private void txtsupplierid6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupplierid6KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid6KeyReleased

    private void txtsupplierid7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplierid7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid7ActionPerformed

    private void txtsupplierid7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupplierid7KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierid7KeyReleased

    private void jButtonsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsubmitActionPerformed
        // TODO add your handling code here:
           
        if((cb_supplier1!= null|| txtsupplierid1 !=null || txtsupplierid2!=null || txtsupplierid3 !=null || 
                  txtsupplierid4 !=null || txtsupplierid5 !=null || txtsupplierid6 !=null|| txtsupplierid7 !=null )){
            
            try
                  {
                
                       Connection conn = MySqlConnection();
                       String qry="insert into financesalary values (?,?,?,?,?,?,?,?)";
                
                      PreparedStatement ps=conn.prepareStatement(qry);
                     
                      
                   
                     ps.setString(1,cb_supplier1.getSelectedItem().toString());
                     ps.setInt(2, Integer.parseInt(txtsupplierid1.getText()));
                      ps.setInt(3, Integer.parseInt(txtsupplierid2.getText()));
                     ps.setInt(4, Integer.parseInt(txtsupplierid3.getText()));
                     ps.setInt(5, Integer.parseInt(txtsupplierid4.getText()));
                     ps.setInt(6, Integer.parseInt(txtsupplierid5.getText()));
                     ps.setInt(7, Integer.parseInt(txtsupplierid6.getText()));
                     ps.setInt(8, Integer.parseInt(txtsupplierid7.getText()));
                     
                     
                     int res=ps.executeUpdate();
                
                     if(res>=1)
                     {
                    
                         JOptionPane.showMessageDialog(null,res+"number of task inserted ");
                     }
                    else
                         
                        JOptionPane.showMessageDialog(null,"insertion fail "); 
                    }
            
                   catch (Exception e) 
                   {
                    
                       JOptionPane.showMessageDialog(null,e);
            
                  }
          }  
        
        
    }//GEN-LAST:event_jButtonsubmitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        MessageFormat header = new MessageFormat("report");
        MessageFormat footer =new MessageFormat("page");

        try{

           jTableEmp.print(JTable.PrintMode.FIT_WIDTH, header, footer);

        }catch(Exception e){
            JOptionPane.showInternalMessageDialog(null, "unable print");

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finance2EmpSAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finance2EmpSAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finance2EmpSAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finance2EmpSAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finance2EmpSAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_supplier1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonsubmit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableEmp;
    private javax.swing.JTextField txtsupplierid1;
    private javax.swing.JTextField txtsupplierid2;
    private javax.swing.JTextField txtsupplierid3;
    private javax.swing.JTextField txtsupplierid4;
    private javax.swing.JTextField txtsupplierid5;
    private javax.swing.JTextField txtsupplierid6;
    private javax.swing.JTextField txtsupplierid7;
    // End of variables declaration//GEN-END:variables
}
