/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import CustomerManagement.AddCustomerBean;
import Interface.Supplieradd;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication1.Inventory.MySqlConnection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sathu
 */
public class Finance5Supplierpay extends javax.swing.JFrame {

    /**
     * Creates new form Finance2
     */
  public Finance5Supplierpay(){
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setVisible(true);
        loadSupplier();
        loadSupplieradd();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       fillTable();
    }
    public ArrayList<Finance5SupplierpayBean>retrieveData(){
        
        ArrayList<Finance5SupplierpayBean> al=null;
        
        al=new ArrayList<Finance5SupplierpayBean>();
        
        try{
            Connection conn=MySqlConnection();
            String qry="select * from financesupplier";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(qry);
            Finance5SupplierpayBean cus;
        
            while(rs.next()){
            
            cus=new Finance5SupplierpayBean(rs.getString("Suppliername"),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6));
             al.add(cus);
        }  
        }
        
        
        catch(Exception e){
            System.out.println(e);
            
        }
        
        return al;
        
    }
    
    public void fillTable(){
        
        ArrayList<Finance5SupplierpayBean> al=retrieveData();
        DefaultTableModel model=(DefaultTableModel)jTableFinance.getModel();
        model.setRowCount(0);
        Object[]row=new Object[6];
                
                for(int i=0; i<al.size(); i++){
                    
                    row[0]=al.get(i).getSuppliername();
                    row[1]=al.get(i).getSupplierid();
                    row[2]=al.get(i).getPrice();
                    row[3]=al.get(i).getWarranty();
                    row[4]=al.get(i).getNoOfQuantity();
                    row[5]=al.get(i).getTotalAmount();
                    
                    model.addRow(row);
                }
        
        
    }
    

    public void loadSupplieradd(){
    
     try {
            Connection conn=MySqlConnection();
            
            String query="SELECT * FROM supplierinventory";
            PreparedStatement ps=conn.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            
            while(rs.next()){
                String SupplierName1=rs.getString("supplierid");
                selectjComboBox.addItem(SupplierName1);
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Supplieradd.class.getName()).log(Level.SEVERE, null,ex);
        }
    
    }
    
    public void loadSupplier(){
    
        try {
            Connection conn=MySqlConnection();
            
            String query="SELECT * FROM newsupplier";
            PreparedStatement ps=conn.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            
            while(rs.next()){
                String SupplierName=rs.getString("companyname");
                cb_supplier.addItem(SupplierName);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_Back = new javax.swing.JButton();
        txtsupplierid = new javax.swing.JTextField();
        cb_supplier = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        selectjComboBox = new javax.swing.JComboBox<>();
        textprice = new javax.swing.JTextField();
        textwarranty = new javax.swing.JTextField();
        textMinQty = new javax.swing.JTextField();
        texttotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFinance = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 0, 51));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1360, 20));

        jButton_Back.setText("BACK");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 40, -1, -1));

        txtsupplierid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplieridActionPerformed(evt);
            }
        });
        txtsupplierid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsupplieridKeyReleased(evt);
            }
        });
        jPanel1.add(txtsupplierid, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 230, 30));

        cb_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_supplierActionPerformed(evt);
            }
        });
        jPanel1.add(cb_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 230, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setText("Supplier Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 170, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setText("Select the SameSupplier ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 310, 80));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setText("Price / Unit");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 150, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setText("Total payment");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 190, 80));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setText("Minimum Qty/Order");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 250, 80));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setText("Supplier ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 190, 80));

        selectjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectjComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(selectjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 230, 40));

        textprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpriceActionPerformed(evt);
            }
        });
        jPanel1.add(textprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 230, 40));

        textwarranty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textwarrantyActionPerformed(evt);
            }
        });
        jPanel1.add(textwarranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 230, 40));
        jPanel1.add(textMinQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 230, 40));

        texttotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        texttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texttotalActionPerformed(evt);
            }
        });
        jPanel1.add(texttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 230, 80));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setText("Warranty Period");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 190, 80));

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 110, 40));

        jTableFinance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SupplierName", "SupplierID", "Price/Unit", "Warranty", "Minimum Qty", "Total Payment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFinance);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 750, 450));

        jButton3.setText("Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 610, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        Finance1 rr= new Finance1();
        rr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void cb_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_supplierActionPerformed
                                                                                                
        try {
            String sName=cb_supplier.getSelectedItem().toString();

            Connection conn=MySqlConnection();
            String query="SELECT * FROM newsupplier WHERE companyname='"+sName+"'";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while(rs.next()){
                Integer sNum=rs.getInt("supplierid");
                txtsupplierid.setText(sNum.toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Finance5Supplierpay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cb_supplierActionPerformed

    private void txtsupplieridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsupplieridKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplieridKeyReleased

    private void txtsupplieridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplieridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplieridActionPerformed

    private void textpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpriceActionPerformed

    private void textwarrantyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textwarrantyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textwarrantyActionPerformed

    private void selectjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectjComboBoxActionPerformed
        // TODO add your handling code here:
                                                                                                        
        try {
            String sNaame=selectjComboBox.getSelectedItem().toString();

            Connection conn=MySqlConnection();
            String query="SELECT * FROM supplierinventory WHERE supplierid='"+sNaame+"'";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while(rs.next()){
               Integer sNum1=rs.getInt("Price");
                textprice.setText(sNum1.toString());
                Integer sNum2=rs.getInt("Warranty");
                textwarranty.setText(sNum2.toString());
                Integer sNum3=rs.getInt("Minquantity");
                textMinQty.setText(sNum3.toString());
                 Integer sNum4=sNum1*sNum3;
                texttotal.setText(sNum4.toString());
                
                
                
                }
        } catch (SQLException ex) {
            Logger.getLogger(Finance5Supplierpay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_selectjComboBoxActionPerformed

    private void texttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texttotalActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        
          
        if((cb_supplier!= null|| txtsupplierid !=null || textprice!=null || textwarranty !=null || 
                  textMinQty !=null || texttotal !=null  )){
            
            try
                  {
                
                       Connection conn = MySqlConnection();
                       String qry="insert into financesupplier values (?,?,?,?,?,?)";
                
                      PreparedStatement ps=conn.prepareStatement(qry);
                     
                      
                   
                     ps.setString(1,cb_supplier.getSelectedItem().toString());
                     ps.setInt(2, Integer.parseInt(txtsupplierid.getText()));
                      ps.setInt(3, Integer.parseInt(textprice.getText()));
                     ps.setInt(4, Integer.parseInt(textMinQty.getText()));
                     ps.setInt(5, Integer.parseInt( textwarranty.getText()));
                     ps.setInt(6, Integer.parseInt( texttotal.getText()));
                     
                     int res=ps.executeUpdate();
                
                     if(res>=1)
                     {
                    
                         JOptionPane.showMessageDialog(null,res+"number of task inserted ");
                     }
                    else
                         
                        JOptionPane.showMessageDialog(null,"insertion fail "); 
                    }
            
                   catch (Exception e) 
                   {
                    
                       JOptionPane.showMessageDialog(null,e);
            
                  }
          }  
        
        
    }//GEN-LAST:event_addbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        MessageFormat header = new MessageFormat("report");
        MessageFormat footer =new MessageFormat("page");

        try{

            jTableFinance.print(JTable.PrintMode.FIT_WIDTH, header, footer);

        }catch(Exception e){
            JOptionPane.showInternalMessageDialog(null, "unable print");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finance5Supplierpay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finance5Supplierpay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finance5Supplierpay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finance5Supplierpay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finance5Supplierpay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JComboBox<String> cb_supplier;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableFinance;
    private javax.swing.JComboBox<String> selectjComboBox;
    private javax.swing.JTextField textMinQty;
    private javax.swing.JTextField textprice;
    private javax.swing.JTextField texttotal;
    private javax.swing.JTextField textwarranty;
    private javax.swing.JTextField txtsupplierid;
    // End of variables declaration//GEN-END:variables

  
}
