/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
        import UI.*;

/**
 *
 * @author sathu
 */
public class Finance1 extends javax.swing.JFrame {

    /**
     * Creates new form Finance1
     */
    public Finance1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton_EMP = new javax.swing.JButton();
        jButton_CUS = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_SUPPLI = new javax.swing.JButton();
        jButton_incomedata = new javax.swing.JButton();
        jButton_incomedata1 = new javax.swing.JButton();
        jButton_INVEN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Suppiler   Payments");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(730, 270, 180, 40);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back-icon (1).png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton1);
        jButton1.setBounds(1220, 20, 110, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("Employee Salary");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(540, 520, 150, 40);

        jButton_EMP.setBackground(new java.awt.Color(51, 153, 255));
        jButton_EMP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_EMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/users-icon.png"))); // NOI18N
        jButton_EMP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_EMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EMPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_EMP);
        jButton_EMP.setBounds(520, 420, 190, 140);

        jButton_CUS.setBackground(new java.awt.Color(51, 153, 255));
        jButton_CUS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_CUS.setText(" Income");
        jButton_CUS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_CUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CUSActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_CUS);
        jButton_CUS.setBounds(970, 440, 230, 130);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("Financial DataBase");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 270, 180, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Finance Managment System");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 10, 690, 80);

        jButton_SUPPLI.setBackground(new java.awt.Color(51, 153, 255));
        jButton_SUPPLI.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_SUPPLI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cash-register-icon.png"))); // NOI18N
        jButton_SUPPLI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_SUPPLI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SUPPLIActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_SUPPLI);
        jButton_SUPPLI.setBounds(720, 170, 200, 140);

        jButton_incomedata.setBackground(new java.awt.Color(51, 153, 255));
        jButton_incomedata.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jButton_incomedata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Actions-go-home-icon.png"))); // NOI18N
        jButton_incomedata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_incomedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_incomedataActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_incomedata);
        jButton_incomedata.setBounds(1080, 20, 110, 60);

        jButton_incomedata1.setBackground(new java.awt.Color(51, 153, 255));
        jButton_incomedata1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jButton_incomedata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Strong-box-money-icon.png"))); // NOI18N
        jButton_incomedata1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_incomedata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_incomedata1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_incomedata1);
        jButton_incomedata1.setBounds(510, 170, 190, 140);

        jButton_INVEN.setBackground(new java.awt.Color(51, 153, 255));
        jButton_INVEN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_INVEN.setText("Repair Inventory");
        jButton_INVEN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_INVEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_INVENActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_INVEN);
        jButton_INVEN.setBounds(960, 170, 220, 140);

        jLabel1.setBackground(new java.awt.Color(204, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/green-wallpaper.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(13, 650));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_EMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EMPActionPerformed
        Finance2EmpSAL rr= new Finance2EmpSAL();
        rr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_EMPActionPerformed

    private void jButton_CUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CUSActionPerformed
        Finance4CustomerIn rr= new Finance4CustomerIn();
        rr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_CUSActionPerformed

    private void jButton_SUPPLIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SUPPLIActionPerformed
        Finance5Supplierpay rr= new Finance5Supplierpay();
        rr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_SUPPLIActionPerformed

    private void jButton_incomedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_incomedataActionPerformed
        Dashboard rr= new Dashboard();
        rr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_incomedataActionPerformed

    private void jButton_INVENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_INVENActionPerformed
                                          
    }//GEN-LAST:event_jButton_INVENActionPerformed

    private void jButton_incomedata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_incomedata1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_incomedata1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finance1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finance1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finance1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finance1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finance1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_CUS;
    private javax.swing.JButton jButton_EMP;
    private javax.swing.JButton jButton_INVEN;
    private javax.swing.JButton jButton_SUPPLI;
    private javax.swing.JButton jButton_incomedata;
    private javax.swing.JButton jButton_incomedata1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
